<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Trending</name>
   <tag></tag>
   <elementGuidId>3c857208-c397-4fe9-b31a-7d672199f7fb</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>listTitle___3cLBo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Trending</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;today container___2vv8Q&quot;]/div[@class=&quot;content___F38wa&quot;]/div[1]/div[@class=&quot;layoutContainer___14Lfd headerPackage___kwByi firstPackageHasTitleOrIsPancake___-WACT zoneAMargin___3WyKB leadType-magazineLead leadPkg-magazineLead&quot;]/div[@class=&quot;railContainer___1BOjV rightRail___1B8Wn layout-rightRail first___3glYg layout-grid-container&quot;]/div[@class=&quot;rail___14Hjt right___v8yG3 layout-grid-item grid-col-5-l grid-col-4-xl&quot;]/div[@class=&quot;railWrapper___OPma9&quot;]/div[@class=&quot;railContent___d7gAe&quot;]/section[@class=&quot;pkg-other teaseList teaseList___30Yoz hasListTitle&quot;]/div[@class=&quot;wrapper___3L-y3&quot;]/h2[@class=&quot;listTitle___3cLBo&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='content']/div/div[7]/div/div/div[3]/div[2]/div/div/section/div/h2</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[5]/following::h2[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nathan Congleton/TODAY'])[2]/following::h2[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pop Culture'])[5]/preceding::h2[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diane Keaton shocked someone found her lost wallet — from 50 years ago'])[2]/preceding::h2[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/div/div/section/div/h2</value>
   </webElementXpaths>
</WebElementEntity>
