<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Subscribe</name>
   <tag></tag>
   <elementGuidId>377d6844-7aea-4836-a279-bbfbe7d0c7da</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subscribe___2m8QQ</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subscribe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;news container___2vv8Q&quot;]/div[@class=&quot;content___F38wa&quot;]/div[1]/div[@class=&quot;layoutContainer___14Lfd zoneAMargin___3WyKB leadType-threeUp&quot;]/div[@class=&quot;layout-rightRailTabbed&quot;]/div[@class=&quot;layout-grid-container hasTitleOrIsPancake___3hwdZ&quot;]/div[@class=&quot;railContainer___1BOjV&quot;]/div[@class=&quot;rail___14Hjt layout-grid-item grid-col-4-l grid-col-3-xl&quot;]/div[@class=&quot;railWrapper___OPma9&quot;]/div[@class=&quot;railContent___d7gAe&quot;]/section[@class=&quot;pkg-other teaseList teaseList___30Yoz hasListTitle&quot;]/div[@class=&quot;wrapper___3L-y3&quot;]/div[@class=&quot;content___3P-Ob&quot;]/div[@class=&quot;newsletter___2DkuV&quot;]/button[@class=&quot;subscribe___2m8QQ&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='content']/div/div[5]/div/div/div[3]/div[2]/div/div[2]/div/div/section/div/div[4]/div/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See All'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marine killed in training accident off coast of Japan identified'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Breaking News'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow Us'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[4]/div/button</value>
   </webElementXpaths>
</WebElementEntity>
