<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Subscribe</name>
   <tag></tag>
   <elementGuidId>0f6fd70c-e9cd-448b-84b4-31cf87b8be02</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subscribe___2m8QQ</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subscribe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;today container___2vv8Q&quot;]/div[@class=&quot;content___F38wa&quot;]/div[1]/div[@class=&quot;layoutContainer___14Lfd headerPackage___kwByi firstPackageHasTitleOrIsPancake___-WACT zoneAMargin___3WyKB leadType-magazineLead leadPkg-magazineLead&quot;]/div[@class=&quot;railContainer___1BOjV rightRail___1B8Wn layout-rightRail first___3glYg layout-grid-container&quot;]/div[@class=&quot;rail___14Hjt right___v8yG3 layout-grid-item grid-col-5-l grid-col-4-xl&quot;]/div[@class=&quot;railWrapper___OPma9&quot;]/div[@class=&quot;railContent___d7gAe&quot;]/section[@class=&quot;pkg-other teaseList teaseList___30Yoz hasListTitle&quot;]/div[@class=&quot;wrapper___3L-y3&quot;]/div[@class=&quot;content___3P-Ob&quot;]/div[@class=&quot;newsletter___2DkuV&quot;]/button[@class=&quot;subscribe___2m8QQ&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='content']/div/div[5]/div/div/div[3]/div[2]/div/div/section/div/div[4]/div/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See All'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free games on TODAY! Start playing our crossword puzzles, sudokus and more!'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up for the TODAY newsletter'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow TODAY'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[4]/div/button</value>
   </webElementXpaths>
</WebElementEntity>
